### ISSUE TITLE
ISE 500 for non-existing entities

### ISSUE THREAD

**Issue by osvetlik** [mareklovci/pia#1]
When I manually modify URL to point to a non-existing entity I get ISE 500 instead of 404 not found:

```
http://localhost:5000/user/20/update
```
![marek-ise500](https://user-images.githubusercontent.com/16480390/71786118-67f1e880-3008-11ea-9563-95a22cabd040.png)

**Comment by mareklovci** [comment]
For retrieving of users from DB I used `user = User.query.filter_by(id=user_id).first()` instead of `user = User.query.get_or_404(user_id)`, like I do everywhere else.

Fixed with commit: d32447bb3c0e1cfda1b156dbe6e6e09a2c2f0173

![2020-01-06](https://user-images.githubusercontent.com/7476297/71796050-46652100-3049-11ea-8686-29f7fa4d6605.png)
